# Generated by Django 4.1.5 on 2023-06-26 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendrier', '0001_initial'),
        ('documents', '0001_initial'),
        ('blog', '0002_article_blog_campaigns'),
        ('galerie', '0001_initial'),
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='blog_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category_blog'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calendrier.calendar'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='documents_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.category_filemanager'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='galerie_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='galerie.category_galerie'),
        ),
    ]
