# Generated by Django 4.1.5 on 2023-07-13 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_blog',
            name='campaigns',
            field=models.ManyToManyField(related_name='articles', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='article_blog',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category_blog'),
        ),
    ]
