# Generated by Django 4.1.5 on 2023-07-31 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_alter_character_campaign_delete_campaign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='charisma',
            new_name='destiny_points',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='constitution',
            new_name='experience',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='character_class',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='dexterity',
            new_name='health_points',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='intelligence',
            new_name='mana_points',
        ),
        migrations.RemoveField(
            model_name='character',
            name='strength',
        ),
        migrations.RemoveField(
            model_name='character',
            name='wisdom',
        ),
        migrations.AddField(
            model_name='character',
            name='sex',
            field=models.CharField(default='ND', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='size',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Wealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold_pieces', models.IntegerField()),
                ('silver_pieces', models.IntegerField()),
                ('copper_pieces', models.IntegerField()),
                ('bank', models.IntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wealth', to='character.character')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='character.character')),
            ],
        ),
        migrations.CreateModel(
            name='MiscellaneousItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miscellaneous_items', to='character.character')),
            ],
        ),
        migrations.CreateModel(
            name='MagicItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magic_items', to='character.character')),
            ],
        ),
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge', to='character.character')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='character.character')),
            ],
        ),
        migrations.CreateModel(
            name='HealingPotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='healing_potions', to='character.character')),
            ],
        ),
        migrations.CreateModel(
            name='FoodDrink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_drinks', to='character.character')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='character.character')),
            ],
        ),
    ]
