# Generated by Django 4.1.5 on 2023-07-31 11:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0005_remove_statistics_strength_statistics_trength_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='fooddrink',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='healingpotion',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='history',
            name='text',
            field=ckeditor.fields.RichTextField(default='Joueur - '),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='magicitem',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='miscellaneousitem',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
