# Generated by Django 4.1.5 on 2023-07-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0006_alter_equipment_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='charisma_malus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistics',
            name='constitution_malus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistics',
            name='dexterity_malus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistics',
            name='intelligence_malus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistics',
            name='perception_malus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistics',
            name='strength_malus',
            field=models.IntegerField(default=0),
        ),
    ]
