# Generated by Django 4.1.5 on 2023-07-31 12:30

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0007_statistics_charisma_malus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('strength_bonus', models.IntegerField(default=0)),
                ('strength_malus', models.IntegerField(default=0)),
                ('dexterity_bonus', models.IntegerField(default=0)),
                ('dexterity_malus', models.IntegerField(default=0)),
                ('constitution_bonus', models.IntegerField(default=0)),
                ('constitution_malus', models.IntegerField(default=0)),
                ('perception_bonus', models.IntegerField(default=0)),
                ('perception_malus', models.IntegerField(default=0)),
                ('charisma_bonus', models.IntegerField(default=0)),
                ('charisma_malus', models.IntegerField(default=0)),
                ('intelligence_bonus', models.IntegerField(default=0)),
                ('intelligence_malus', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.RenameField(
            model_name='statistics',
            old_name='trength',
            new_name='strength',
        ),
        migrations.RemoveField(
            model_name='knowledge',
            name='character',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='charisma_bonus',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='charisma_malus',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='constitution_bonus',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='constitution_malus',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='dexterity_bonus',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='dexterity_malus',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='intelligence_bonus',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='intelligence_malus',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='perception_bonus',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='perception_malus',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='strength_bonus',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='strength_malus',
        ),
        migrations.AlterField(
            model_name='statistics',
            name='character',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='character.character'),
        ),
        migrations.CreateModel(
            name='CharacterSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.character')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.skill')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength_bonus', models.IntegerField(default=0)),
                ('strength_malus', models.IntegerField(default=0)),
                ('dexterity_bonus', models.IntegerField(default=0)),
                ('dexterity_malus', models.IntegerField(default=0)),
                ('constitution_bonus', models.IntegerField(default=0)),
                ('constitution_malus', models.IntegerField(default=0)),
                ('perception_bonus', models.IntegerField(default=0)),
                ('perception_malus', models.IntegerField(default=0)),
                ('charisma_bonus', models.IntegerField(default=0)),
                ('charisma_malus', models.IntegerField(default=0)),
                ('intelligence_bonus', models.IntegerField(default=0)),
                ('intelligence_malus', models.IntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.character')),
                ('knowledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.knowledge')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='knowledges',
            field=models.ManyToManyField(blank=True, through='character.CharacterKnowledge', to='character.knowledge'),
        ),
        migrations.AddField(
            model_name='character',
            name='skills',
            field=models.ManyToManyField(blank=True, through='character.CharacterSkill', to='character.skill'),
        ),
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.race'),
        ),
    ]
